language: java
jdk:
  - openjdk11

os: 
  - linux
  
dist:
  - debian
  
addons:
    sonarcloud:
        organization: "jacopofabi"
        token: "841430d7c783c98e9b8b4289d18395894be4d3d1"
        
script: 
    # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean verify sonar:sonar -Pcoverage -X
    # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install sonar:sonar -Pcoverage -PnoTest -X
  #- mvn clean verify sonar:sonar -Dsonar.projectKey=jacopofabi_bookkeeper -PnoTest
  - mvn "-Dtest=org/apache/avro/mytests/*Test" -DfailIfNoTests=false clean verify -e org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=jacopofabi_avro